server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useSSL=false
    username: root
    password: 1233
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: DevDigi@123

app:
  elasticpath:
    url: https://useast.api.elasticpath.com
    url-v2: https://useast.api.elasticpath.com/v2
    client-id: ukpTS09amWLAsnVj2uaIzvg19gN5ccxJslIKssolYN
    store-id: cb7e65c2-4c75-4163-b4bf-47dfa5782505
    client-secret: ivE9Sw5bQRYJA12UrYV63gasbBEf0L7oL67w1coYz6
    grand-type: client_credentials
  jwt:
    secret: haivo
    access-token-validity-in-seconds: 60