server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useSSL=false
    username: root
    password: 1233
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

app:
  elasticpath:
    url: https://useast.api.elasticpath.com
    urlV2: https://useast.api.elasticpath.com/v2
    clientID: ogcFRDog273HKSuTEt4h06vp7iXQCYtrpvMyfX0Ttj
    storeID: 349f53f5-c546-4c90-83ff-bbb2eb015064
    clientSecret: Q9kbwjVYGKCZHdu4n9p4X5CfxMnhEJhChgHVNil4WJ
    grand-type: client_credentials