server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 15672
    username: dev
    password: DevDigi@123

app:
  jwt:
    secret: haivo
    access-token-validity-in-seconds: 3600