version: "3"
services:
  ecommerce:
    image: ecommerce
    ports:
      - "8080:8080"
    networks:
      - ecommerce-mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    networks:
      - ecommerce-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce

networks:
  ecommerce-mysql: